# SPDX-FileCopyrightText: 2026 José Ángel Soler Ortiz
# SPDX-License-Identifier: AGPL-3.0-or-later

include_guard(GLOBAL)

if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
	list(APPEND IMOGRIFY_CXX_COMPILE_DEFINITIONS IMOGRIFY_OS_LINUX=0 IMOGRIFY_OS_WINDOWS=1)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
	list(APPEND IMOGRIFY_CXX_COMPILE_DEFINITIONS IMOGRIFY_OS_LINUX=1 IMOGRIFY_OS_WINDOWS=0)
else()
	list(APPEND IMOGRIFY_CXX_COMPILE_DEFINITIONS IMOGRIFY_OS_LINUX=0 IMOGRIFY_OS_WINDOWS=0)
	message(WARNING "Operative system ${CMAKE_SYSTEM_NAME} is not supported by ${CMAKE_PROJECT_NAME}.")
endif()
