# Copyright (c) 2020 GitHub
# Copyright (c) 2024 Imogrify contributors
# File licensed under the MIT license (see ci_LICENSE for details).
# Based on: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml

name: Continuous integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ macos-15-arm64, ubuntu-24.04, windows-latest ]
        compiler: [ clang, gcc, msvc ]
        include:
          - os: macos-15-arm64
            build_type: release
            cmake_os: macos
          - os: ubuntu-24.04
            build_type: debug
            cmake_os: linux
          - os: windows-latest
            build_type: release
            cmake_os: windows
        exclude:
          - os: macos-15-arm64
            compiler: gcc
          - os: macos-15-arm64
            compiler: msvc
          - os: ubuntu-24.04
            compiler: msvc
          - os: windows-latest
            compiler: clang
          - os: windows-latest
            compiler: gcc

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup MSVC
        if: matrix.compiler == 'msvc'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        env:
          VCPKG_DISABLE_METRICS: 1
        with:
          # Must be updated along with cmake/dependencies/vcpkg.cmake.
          vcpkgGitCommitId: 'c82f74667287d3dc386bce81e44964370c91a289' # 2024.09.30

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build dependencies
        run: pip install ninja

      - name: Configure project
        run: cmake --preset ci-cfg-${{ matrix.cmake_os }}-${{ matrix.build_type }}-${{ matrix.compiler }}

      - name: Build project
        run: cmake --build --preset ci-build-${{ matrix.cmake_os }}-${{ matrix.build_type }}-${{ matrix.compiler }}

      - name: Run tests
        run: ctest --preset ci-test-${{ matrix.cmake_os }}-${{ matrix.build_type }}-${{ matrix.compiler }} --output-on-failure
