# Copyright (c) 2020 GitHub
# Copyright (c) 2024 Imogrify contributors
# File licensed under the MIT license (see build_checks_LICENSE for details).
# Based on: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml

name: Continuous integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ macos-latest, ubuntu-24.04, windows-latest ]
        build_type: [ debug, release ]
        exclude:
          - os: macos-latest
            build_type: release
          - os: ubuntu-24.04
            build_type: debug
          - os: windows-latest
            build_type: release

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build dependencies
        run: pip install meson ninja

      - name: Configure project
        # Enable all warnings and warnings as errors.
        # forcefallback ensures that all dependencies are present.
        # clang-format and clang-tidy are executed on separate CI steps.
        run: meson setup --warnlevel 3 --werror --wrap-mode forcefallback --buildtype ${{ matrix.build_type }} -Dtest_clang_format=false -Dtest_clang_tidy=false build_${{ matrix.build_type }}

      - name: Build project
        run: meson compile -v -C build_${{ matrix.build_type }}

      - name: Run tests
        run: meson test -v -C build_${{ matrix.build_type }}

      - name: clang-format warnings
        if: matrix.os == 'ubuntu-24.04'
        run: ninja -v -C build_${{ matrix.build_type }} clang-format-check

      - name: clang-tidy warnings
        if: matrix.os == 'ubuntu-24.04'
        run: ninja -v -C build_${{ matrix.build_type }} clang-tidy
