name: clang-format check
on:
  pull_request:
    branches: ["main"]

jobs:
  clang-format-check:
    name: clang-format-check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Run clang-format checks
      uses: jidicula/clang-format-action@v4.15.0
      with:
        clang-format-version: '20'
        check-path: 'imogrify'
