name: cpp-linter
on:
  pull_request:
    branches: ["main"]

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install build dependencies
        run: pip install ninja

      - name: Install project dependencies
        run: sudo apt-get install -y catch2 libconcurrentqueue-dev libfmt-dev

      - name: CMake configure
        run: cmake --preset system-linux-gcc-release

      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        continue-on-error: true
        with:
          version: 21
          style: 'file'   # Use .clang-format config file
          tidy-checks: '' # Use .clang-tidy config file
          files-changed-only: false
          # only 'update' a single comment in a pull request thread.
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
